import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight, Clock3, Phone } from "lucide-react";
import { formatDate } from "../../lib/format";

export default function CallQueue({ followUps = [], loading }) {
  const calls = followUps.filter((item) => item.status === "Today" || item.status === "Overdue").slice(0, 4);
  return <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.15 }} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-800">Today&apos;s Call Queue</p><p className="mt-1 text-sm text-slate-500">Priority follow-ups due today</p></div><Link href="/follow-ups" className="flex items-center gap-1 text-sm font-semibold text-indigo-600 transition hover:text-indigo-700">View all<ArrowUpRight size={16} /></Link></div><div className="mt-6 divide-y divide-slate-100">{loading ? <p className="py-8 text-center text-sm text-slate-500">Loading calls…</p> : calls.length ? calls.map((call) => <div key={call.id} className="flex items-center gap-3 py-4 first:pt-0 last:pb-0"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Phone size={18} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-700">{call.patientName}</p><p className="mt-1 text-xs text-slate-400">{call.category}</p></div><div className="hidden text-right sm:block"><p className="flex items-center justify-end gap-1 text-xs font-medium text-slate-500"><Clock3 size={14} />{formatDate(call.dueDate, { hour: "numeric", minute: "2-digit" })}</p><p className={`mt-1 text-xs font-semibold ${call.status === "Overdue" ? "text-rose-500" : "text-amber-500"}`}>{call.status}</p></div><Link href="/follow-ups" className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-600">Open</Link></div>) : <p className="py-8 text-center text-sm text-slate-500">No calls need attention today.</p>}</div></motion.section>;
}
